import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://parabank.parasoft.com/parabank/index.htm');
  await page.locator('input[name="username"]').click();
  await page.locator('input[name="username"]').fill('spiderman_123');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('Mary_jane123');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('link', { name: 'Bill Pay' }).click();
  await page.locator('input[name="payee.name"]').click();
  await page.locator('input[name="payee.name"]').fill('Albert Pettersen');
  await page.locator('input[name="payee.address.street"]').click();
  await page.locator('input[name="payee.address.street"]').click();
  await page.locator('input[name="payee.address.street"]').fill('Baddie Street');
  await page.locator('input[name="payee.address.street"]').click();
  await page.locator('input[name="payee.address.street"]').click();
  await page.locator('input[name="payee.address.street"]').click();
  await page.locator('input[name="payee.address.street"]').press('ArrowLeft');
  await page.locator('input[name="payee.address.street"]').press('ArrowLeft');
  await page.locator('input[name="payee.address.street"]').press('ArrowLeft');
  await page.locator('input[name="payee.address.street"]').press('ArrowLeft');
  await page.locator('input[name="payee.address.street"]').press('ArrowLeft');
  await page.locator('input[name="payee.address.street"]').press('ArrowLeft');
  await page.locator('input[name="payee.address.street"]').press('ArrowLeft');
  await page.locator('input[name="payee.address.street"]').press('ArrowLeft');
  await page.locator('input[name="payee.address.street"]').press('ArrowLeft');
  await page.locator('input[name="payee.address.street"]').press('ArrowLeft');
  await page.locator('input[name="payee.address.street"]').press('ArrowLeft');
  await page.locator('input[name="payee.address.street"]').fill('212 Baddie Street');
  await page.locator('input[name="payee.address.city"]').click();
  await page.locator('input[name="payee.address.city"]').fill('');
  await page.locator('input[name="payee.address.state"]').click();
  await page.locator('input[name="payee.address.state"]').fill('New York');
  await page.locator('input[name="payee.address.city"]').click();
  await page.locator('input[name="payee.address.city"]').fill('New York City');
  await page.locator('input[name="payee.address.zipCode"]').click();
  await page.locator('input[name="payee.address.zipCode"]').fill('12345');
  await page.locator('input[name="payee.phoneNumber"]').click();
  await page.locator('input[name="payee.phoneNumber"]').fill('1234567890');
  await page.locator('input[name="payee.accountNumber"]').click();
  await page.locator('input[name="payee.accountNumber"]').fill('1');
});